import type { Block } from 'payload'

export const Code: Block = {
  slug: 'code',
  interfaceName: 'CodeBlock',
  fields: [
    {
      name: 'language',
      type: 'select',
      options: [
        { label: 'ActionScript', value: 'actionscript' },
        { label: 'Ada', value: 'ada' },
        { label: 'Apache Config', value: 'apacheconf' },
        { label: 'Apex', value: 'apex' },
        { label: 'AppleScript', value: 'applescript' },
        { label: 'Arduino', value: 'arduino' },
        { label: 'Assembly', value: 'asm6502' },
        { label: 'AutoHotkey', value: 'autohotkey' },
        { label: 'Bash', value: 'bash' },
        { label: 'BASIC', value: 'basic' },
        { label: 'Batch', value: 'batch' },
        { label: 'C', value: 'c' },
        { label: 'C#', value: 'csharp' },
        { label: 'C++', value: 'cpp' },
        { label: 'Clojure', value: 'clojure' },
        { label: 'CMake', value: 'cmake' },
        { label: 'CoffeeScript', value: 'coffeescript' },
        { label: 'CSS', value: 'css' },
        { label: 'D', value: 'd' },
        { label: 'Dart', value: 'dart' },
        { label: 'Diff', value: 'diff' },
        { label: 'Django', value: 'django' },
        { label: 'Docker', value: 'docker' },
        { label: 'Elixir', value: 'elixir' },
        { label: 'Elm', value: 'elm' },
        { label: 'Erlang', value: 'erlang' },
        { label: 'F#', value: 'fsharp' },
        { label: 'Fortran', value: 'fortran' },
        { label: 'Go', value: 'go' },
        { label: 'GraphQL', value: 'graphql' },
        { label: 'Groovy', value: 'groovy' },
        { label: 'Haskell', value: 'haskell' },
        { label: 'HCL', value: 'hcl' },
        { label: 'HTML', value: 'html' },
        { label: 'HTTP', value: 'http' },
        { label: 'Java', value: 'java' },
        { label: 'JavaScript', value: 'javascript' },
        { label: 'JSON', value: 'json' },
        { label: 'JSX', value: 'jsx' },
        { label: 'Julia', value: 'julia' },
        { label: 'Kotlin', value: 'kotlin' },
        { label: 'LaTeX', value: 'latex' },
        { label: 'Less', value: 'less' },
        { label: 'Lisp', value: 'lisp' },
        { label: 'Lua', value: 'lua' },
        { label: 'Makefile', value: 'makefile' },
        { label: 'Markdown', value: 'markdown' },
        { label: 'MATLAB', value: 'matlab' },
        { label: 'Nginx', value: 'nginx' },
        { label: 'Objective-C', value: 'objectivec' },
        { label: 'OCaml', value: 'ocaml' },
        { label: 'Pascal', value: 'pascal' },
        { label: 'Perl', value: 'perl' },
        { label: 'PHP', value: 'php' },
        { label: 'PowerShell', value: 'powershell' },
        { label: 'Prolog', value: 'prolog' },
        { label: 'Protocol Buffers', value: 'protobuf' },
        { label: 'Python', value: 'python' },
        { label: 'R', value: 'r' },
        { label: 'Ruby', value: 'ruby' },
        { label: 'Rust', value: 'rust' },
        { label: 'SAS', value: 'sas' },
        { label: 'Sass (Sass)', value: 'sass' },
        { label: 'Sass (Scss)', value: 'scss' },
        { label: 'Scala', value: 'scala' },
        { label: 'Scheme', value: 'scheme' },
        { label: 'Shell', value: 'shell' },
        { label: 'Solidity', value: 'solidity' },
        { label: 'SQL', value: 'sql' },
        { label: 'Swift', value: 'swift' },
        { label: 'TOML', value: 'toml' },
        { label: 'TSX', value: 'tsx' },
        { label: 'TypeScript', value: 'typescript' },
        { label: 'VB.NET', value: 'vbnet' },
        { label: 'Verilog', value: 'verilog' },
        { label: 'VHDL', value: 'vhdl' },
        { label: 'Visual Basic', value: 'visual-basic' },
        { label: 'WebAssembly', value: 'wasm' },
        { label: 'Wiki', value: 'wiki' },
        { label: 'YAML', value: 'yaml' },
        { label: 'Zig', value: 'zig' },
      ],
      defaultValue: 'typescript',
    },
    {
      name: 'code',
      type: 'code',
      label: false,
      required: true,
    },
  ],
}
