'use client'

import { Sparkles, Loader2 } from 'lucide-react'
import React, { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'

type Props = {
  content: string
}

export const SummarizeButton: React.FC<Props> = ({ content }) => {
  const [summary, setSummary] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [open, setOpen] = useState(false)

  const handleSummarize = async () => {
    if (summary) return

    setLoading(true)
    try {
      const response = await fetch('/api/summarize', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ content }),
      })

      if (!response.ok) {
        throw new Error('Failed to fetch summary')
      }

      const data = await response.json()
      setSummary(data.summary)
    } catch (error) {
      console.error('Error summarizing:', error)
      setSummary('Failed to generate summary. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2 text-xs" onClick={handleSummarize}>
          <Sparkles className="h-3.5 w-3.5 text-yellow-500" />
          Summarize with AI
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-yellow-500" />
            AI Summary
          </DialogTitle>
          <DialogDescription>
            A concise summary of the article generated by AI.
          </DialogDescription>
        </DialogHeader>
        <div className="mt-4 text-sm leading-relaxed text-muted-foreground max-h-[60vh] overflow-y-auto">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-8 gap-3">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <p className="text-xs">Analyzing content...</p>
            </div>
          ) : (
            <p className="whitespace-pre-line">{summary}</p>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}
